// Dicionário de traduções do Gym101%.
// Cada chave corresponde a um texto fixo da interface.
const TRADUCOES = {
    pt: {
        marca_tagline: "GYM101%",
        nav_painel: "Painel", nav_progresso: "Progresso", nav_alimentacao: "Alimentação",
        nav_amigos: "Amigos", nav_desafios: "Desafios", nav_sair: "Sair",

        // Login
        login_titulo: "Entrar na conta",
        login_sem_conta: "Ainda não tens conta?",
        login_criar_aqui: "Cria uma aqui",
        login_email: "Email",
        login_password: "Palavra-passe",
        login_botao: "Entrar",
        login_hero_titulo_1: "Treina. Regista.",
        login_hero_titulo_2: "Compete com os",
        login_hero_titulo_3: "teus.",
        login_hero_texto: "O Gym101% junta o teu treino, a tua alimentação e os teus amigos num único sítio. Sem desculpas, só resultados.",

        // Registo
        registo_titulo: "Criar conta",
        registo_tem_conta: "Já tens conta?",
        registo_entrar_aqui: "Entra aqui",
        registo_nome: "Nome",
        registo_password_dica: "Mínimo 6 caracteres.",
        registo_botao: "Criar a minha conta",
        registo_hero_titulo_1: "A tua evolução,",
        registo_hero_titulo_2: "com",
        registo_hero_titulo_2b: "números",
        registo_hero_titulo_3: "à frente.",
        registo_hero_texto: "Regista treinos, pesa-te, planeia as refeições e desafia os teus amigos para veres quem chega mais longe este mês.",

        // Dashboard
        dash_titulo: "Bem-vindo de volta.",
        dash_subtitulo: "Aqui está o resumo da tua semana.",
        dash_stat_treinos: "Treinos este mês",
        dash_stat_peso: "Peso atual (kg)",
        dash_stat_amigos: "Amigos a competir",
        dash_ultimos_treinos: "Últimos treinos",
        dash_treino_placeholder: "Ex: Peito e tríceps",
        dash_registar_treino: "Registar treino de hoje",
        dash_desafios_ativos: "Desafios ativos",
        dash_ver_desafios: "Ver todos os desafios",
        dash_sem_treinos: "Ainda não registaste nenhum treino. Começa hoje.",
        dash_sem_desafios: "Sem desafios a decorrer. Cria um na aba Desafios.",
        dash_ate: "até",
        dash_a_carregar: "A carregar…",

        // Progresso
        prog_titulo: "O teu progresso",
        prog_subtitulo: "Cada registo conta uma parte da história.",
        prog_novo_registo: "Novo registo",
        prog_data: "Data",
        prog_peso: "Peso (kg)",
        prog_gordura: "Massa gorda (%)",
        prog_musculo: "Massa muscular (%)",
        prog_notas: "Notas",
        prog_notas_placeholder: "Como te sentiste, o que mudaste...",
        prog_guardar: "Guardar registo",
        prog_evolucao: "Evolução do peso",
        prog_evolucao_sub: "Últimos registos, do mais antigo ao mais recente.",
        prog_historico: "Histórico",
        prog_th_data: "Data", prog_th_peso: "Peso", prog_th_gordura: "Massa gorda",
        prog_th_musculo: "Massa muscular", prog_th_notas: "Notas",
        prog_remover: "remover",
        prog_sem_registos: "Sem registos ainda. Preenche o formulário ao lado.",
        prog_grafico_vazio: "Precisas de pelo menos 2 registos para veres o gráfico.",

        // Alimentação
        alim_titulo: "Alimentação",
        alim_subtitulo: "O que comeste hoje,",
        alim_resumo: "Resumo do dia",
        alim_calorias: "Calorias",
        alim_proteina: "Proteína", alim_hidratos: "Hidratos", alim_gordura: "Gordura",
        alim_metas_titulo: "Definir as tuas metas diárias",
        alim_meta_calorias: "Calorias", alim_meta_proteina: "Proteína (g)",
        alim_meta_hidratos: "Hidratos (g)", alim_meta_gordura: "Gordura (g)",
        alim_atualizar_metas: "Atualizar metas",
        alim_adicionar_refeicao: "Adicionar refeição",
        alim_nome: "Nome", alim_nome_placeholder: "Ex: Peito de frango com arroz",
        alim_tipo: "Tipo",
        alim_tipo_pequeno_almoco: "Pequeno-almoço", alim_tipo_almoco: "Almoço",
        alim_tipo_lanche: "Lanche", alim_tipo_jantar: "Jantar", alim_tipo_ceia: "Ceia",
        alim_kcal: "Kcal", alim_prot_g: "Prot. (g)", alim_hid_g: "Hid. (g)", alim_gord_g: "Gord. (g)",
        alim_adicionar: "Adicionar",
        alim_refeicoes_registadas: "Refeições registadas",
        alim_remover: "remover",
        alim_sem_refeicoes: "Ainda não registaste refeições neste dia.",

        // Amigos
        amigos_titulo: "Amigos",
        amigos_subtitulo: "Treinar sozinho é mais difícil. Junta gente à tua volta.",
        amigos_pesquisar_titulo: "Encontrar pessoas",
        amigos_pesquisar_placeholder: "Procura por nome ou email...",
        amigos_pesquisar_botao: "Pesquisar",
        amigos_nenhum_encontrado: "Ninguém encontrado com esse nome ou email.",
        amigos_adicionar: "Adicionar",
        amigos_pedido_enviado: "Pedido enviado",
        amigos_pedidos_pendentes: "Pedidos pendentes",
        amigos_sem_pedidos: "Sem pedidos por aceitar.",
        amigos_aceitar: "Aceitar", amigos_recusar: "Recusar",
        amigos_os_teus: "Os teus amigos",
        amigos_sem_amigos: "Ainda não tens amigos no Gym101%. Pesquisa acima.",
        amigos_treinos: "treinos",

        // Desafios
        des_titulo: "Desafios",
        des_subtitulo: "Cria uma competição e convida os teus amigos. Quem chega primeiro à meta?",
        des_novo: "+ Novo desafio",
        des_criar_titulo: "Criar desafio",
        des_nome: "Nome do desafio", des_nome_placeholder: "Ex: Quem treina mais em outubro",
        des_tipo: "Tipo de competição",
        des_tipo_treinos: "Nº de treinos", des_tipo_calorias: "Calorias queimadas", des_tipo_peso: "Peso perdido",
        des_data_inicio: "Data de início", des_data_fim: "Data de fim",
        des_descricao: "Descrição (opcional)", des_descricao_placeholder: "Regras, prémio para o vencedor...",
        des_convidar: "Convidar amigos",
        des_sem_amigos: "Ainda não tens amigos para convidar. Vai à aba Amigos primeiro.",
        des_criar_botao: "Criar desafio",
        des_sem_desafios: "Ainda não estás em nenhum desafio. Cria o primeiro!",
        des_nao_comecou: "Ainda não começou", des_terminado: "Terminado", des_a_decorrer: "A decorrer",
        des_sem_pontos: "Ainda sem pontos registados.", des_pts: "pts",
        des_a_carregar: "A carregar desafios…"
    },

    en: {
        marca_tagline: "GYM101%",
        nav_painel: "Dashboard", nav_progresso: "Progress", nav_alimentacao: "Nutrition",
        nav_amigos: "Friends", nav_desafios: "Challenges", nav_sair: "Log out",

        login_titulo: "Sign in",
        login_sem_conta: "Don't have an account yet?",
        login_criar_aqui: "Create one here",
        login_email: "Email",
        login_password: "Password",
        login_botao: "Sign in",
        login_hero_titulo_1: "Train. Track.",
        login_hero_titulo_2: "Compete with your",
        login_hero_titulo_3: "crew.",
        login_hero_texto: "Gym101% brings your workouts, your meals and your friends together in one place. No excuses, just results.",

        registo_titulo: "Create account",
        registo_tem_conta: "Already have an account?",
        registo_entrar_aqui: "Sign in here",
        registo_nome: "Name",
        registo_password_dica: "Minimum 6 characters.",
        registo_botao: "Create my account",
        registo_hero_titulo_1: "Your progress,",
        registo_hero_titulo_2: "backed by",
        registo_hero_titulo_2b: "numbers",
        registo_hero_titulo_3: ".",
        registo_hero_texto: "Log workouts, weigh in, plan your meals and challenge your friends to see who goes further this month.",

        dash_titulo: "Welcome back.",
        dash_subtitulo: "Here's your week at a glance.",
        dash_stat_treinos: "Workouts this month",
        dash_stat_peso: "Current weight (kg)",
        dash_stat_amigos: "Friends competing",
        dash_ultimos_treinos: "Recent workouts",
        dash_treino_placeholder: "E.g. Chest and triceps",
        dash_registar_treino: "Log today's workout",
        dash_desafios_ativos: "Active challenges",
        dash_ver_desafios: "View all challenges",
        dash_sem_treinos: "You haven't logged a workout yet. Start today.",
        dash_sem_desafios: "No challenges running. Create one in the Challenges tab.",
        dash_ate: "until",
        dash_a_carregar: "Loading…",

        prog_titulo: "Your progress",
        prog_subtitulo: "Every entry tells part of the story.",
        prog_novo_registo: "New entry",
        prog_data: "Date",
        prog_peso: "Weight (kg)",
        prog_gordura: "Body fat (%)",
        prog_musculo: "Muscle mass (%)",
        prog_notas: "Notes",
        prog_notas_placeholder: "How you felt, what changed...",
        prog_guardar: "Save entry",
        prog_evolucao: "Weight trend",
        prog_evolucao_sub: "Recent entries, oldest to newest.",
        prog_historico: "History",
        prog_th_data: "Date", prog_th_peso: "Weight", prog_th_gordura: "Body fat",
        prog_th_musculo: "Muscle mass", prog_th_notas: "Notes",
        prog_remover: "remove",
        prog_sem_registos: "No entries yet. Fill in the form on the side.",
        prog_grafico_vazio: "You need at least 2 entries to see the chart.",

        alim_titulo: "Nutrition",
        alim_subtitulo: "What you ate today,",
        alim_resumo: "Today's summary",
        alim_calorias: "Calories",
        alim_proteina: "Protein", alim_hidratos: "Carbs", alim_gordura: "Fat",
        alim_metas_titulo: "Set your daily targets",
        alim_meta_calorias: "Calories", alim_meta_proteina: "Protein (g)",
        alim_meta_hidratos: "Carbs (g)", alim_meta_gordura: "Fat (g)",
        alim_atualizar_metas: "Update targets",
        alim_adicionar_refeicao: "Add meal",
        alim_nome: "Name", alim_nome_placeholder: "E.g. Chicken breast with rice",
        alim_tipo: "Type",
        alim_tipo_pequeno_almoco: "Breakfast", alim_tipo_almoco: "Lunch",
        alim_tipo_lanche: "Snack", alim_tipo_jantar: "Dinner", alim_tipo_ceia: "Late snack",
        alim_kcal: "Kcal", alim_prot_g: "Prot. (g)", alim_hid_g: "Carbs (g)", alim_gord_g: "Fat (g)",
        alim_adicionar: "Add",
        alim_refeicoes_registadas: "Logged meals",
        alim_remover: "remove",
        alim_sem_refeicoes: "No meals logged for this day yet.",

        amigos_titulo: "Friends",
        amigos_subtitulo: "Training alone is harder. Bring people along.",
        amigos_pesquisar_titulo: "Find people",
        amigos_pesquisar_placeholder: "Search by name or email...",
        amigos_pesquisar_botao: "Search",
        amigos_nenhum_encontrado: "No one found with that name or email.",
        amigos_adicionar: "Add",
        amigos_pedido_enviado: "Request sent",
        amigos_pedidos_pendentes: "Pending requests",
        amigos_sem_pedidos: "No requests to accept.",
        amigos_aceitar: "Accept", amigos_recusar: "Decline",
        amigos_os_teus: "Your friends",
        amigos_sem_amigos: "You don't have any friends on Gym101% yet. Search above.",
        amigos_treinos: "workouts",

        des_titulo: "Challenges",
        des_subtitulo: "Start a competition and invite your friends. Who gets there first?",
        des_novo: "+ New challenge",
        des_criar_titulo: "Create challenge",
        des_nome: "Challenge name", des_nome_placeholder: "E.g. Who trains most in October",
        des_tipo: "Competition type",
        des_tipo_treinos: "Number of workouts", des_tipo_calorias: "Calories burned", des_tipo_peso: "Weight lost",
        des_data_inicio: "Start date", des_data_fim: "End date",
        des_descricao: "Description (optional)", des_descricao_placeholder: "Rules, prize for the winner...",
        des_convidar: "Invite friends",
        des_sem_amigos: "You don't have any friends to invite yet. Go to the Friends tab first.",
        des_criar_botao: "Create challenge",
        des_sem_desafios: "You're not in any challenge yet. Create the first one!",
        des_nao_comecou: "Not started yet", des_terminado: "Finished", des_a_decorrer: "Ongoing",
        des_sem_pontos: "No points logged yet.", des_pts: "pts",
        des_a_carregar: "Loading challenges…"
    },

    es: {
        marca_tagline: "GYM101%",
        nav_painel: "Panel", nav_progresso: "Progreso", nav_alimentacao: "Alimentación",
        nav_amigos: "Amigos", nav_desafios: "Retos", nav_sair: "Salir",

        login_titulo: "Iniciar sesión",
        login_sem_conta: "¿Todavía no tienes cuenta?",
        login_criar_aqui: "Crea una aquí",
        login_email: "Correo electrónico",
        login_password: "Contraseña",
        login_botao: "Entrar",
        login_hero_titulo_1: "Entrena. Registra.",
        login_hero_titulo_2: "Compite con los",
        login_hero_titulo_3: "tuyos.",
        login_hero_texto: "Gym101% reúne tu entrenamiento, tu alimentación y tus amigos en un solo sitio. Sin excusas, solo resultados.",

        registo_titulo: "Crear cuenta",
        registo_tem_conta: "¿Ya tienes cuenta?",
        registo_entrar_aqui: "Entra aquí",
        registo_nome: "Nombre",
        registo_password_dica: "Mínimo 6 caracteres.",
        registo_botao: "Crear mi cuenta",
        registo_hero_titulo_1: "Tu evolución,",
        registo_hero_titulo_2: "con",
        registo_hero_titulo_2b: "números",
        registo_hero_titulo_3: "por delante.",
        registo_hero_texto: "Registra entrenamientos, pésate, planifica tus comidas y reta a tus amigos para ver quién llega más lejos este mes.",

        dash_titulo: "Bienvenido de nuevo.",
        dash_subtitulo: "Aquí tienes el resumen de tu semana.",
        dash_stat_treinos: "Entrenamientos este mes",
        dash_stat_peso: "Peso actual (kg)",
        dash_stat_amigos: "Amigos compitiendo",
        dash_ultimos_treinos: "Últimos entrenamientos",
        dash_treino_placeholder: "Ej: Pecho y tríceps",
        dash_registar_treino: "Registrar entrenamiento de hoy",
        dash_desafios_ativos: "Retos activos",
        dash_ver_desafios: "Ver todos los retos",
        dash_sem_treinos: "Todavía no has registrado ningún entrenamiento. Empieza hoy.",
        dash_sem_desafios: "No hay retos en curso. Crea uno en la pestaña Retos.",
        dash_ate: "hasta",
        dash_a_carregar: "Cargando…",

        prog_titulo: "Tu progreso",
        prog_subtitulo: "Cada registro cuenta parte de la historia.",
        prog_novo_registo: "Nuevo registro",
        prog_data: "Fecha",
        prog_peso: "Peso (kg)",
        prog_gordura: "Grasa corporal (%)",
        prog_musculo: "Masa muscular (%)",
        prog_notas: "Notas",
        prog_notas_placeholder: "Cómo te sentiste, qué cambió...",
        prog_guardar: "Guardar registro",
        prog_evolucao: "Evolución del peso",
        prog_evolucao_sub: "Últimos registros, del más antiguo al más reciente.",
        prog_historico: "Historial",
        prog_th_data: "Fecha", prog_th_peso: "Peso", prog_th_gordura: "Grasa corporal",
        prog_th_musculo: "Masa muscular", prog_th_notas: "Notas",
        prog_remover: "eliminar",
        prog_sem_registos: "Todavía no hay registros. Completa el formulario al lado.",
        prog_grafico_vazio: "Necesitas al menos 2 registros para ver el gráfico.",

        alim_titulo: "Alimentación",
        alim_subtitulo: "Lo que comiste hoy,",
        alim_resumo: "Resumen del día",
        alim_calorias: "Calorías",
        alim_proteina: "Proteína", alim_hidratos: "Carbohidratos", alim_gordura: "Grasa",
        alim_metas_titulo: "Define tus objetivos diarios",
        alim_meta_calorias: "Calorías", alim_meta_proteina: "Proteína (g)",
        alim_meta_hidratos: "Carbohidratos (g)", alim_meta_gordura: "Grasa (g)",
        alim_atualizar_metas: "Actualizar objetivos",
        alim_adicionar_refeicao: "Añadir comida",
        alim_nome: "Nombre", alim_nome_placeholder: "Ej: Pechuga de pollo con arroz",
        alim_tipo: "Tipo",
        alim_tipo_pequeno_almoco: "Desayuno", alim_tipo_almoco: "Almuerzo",
        alim_tipo_lanche: "Merienda", alim_tipo_jantar: "Cena", alim_tipo_ceia: "Resopón",
        alim_kcal: "Kcal", alim_prot_g: "Prot. (g)", alim_hid_g: "Carb. (g)", alim_gord_g: "Grasa (g)",
        alim_adicionar: "Añadir",
        alim_refeicoes_registadas: "Comidas registradas",
        alim_remover: "eliminar",
        alim_sem_refeicoes: "Todavía no has registrado comidas en este día.",

        amigos_titulo: "Amigos",
        amigos_subtitulo: "Entrenar solo es más difícil. Rodéate de gente.",
        amigos_pesquisar_titulo: "Buscar personas",
        amigos_pesquisar_placeholder: "Busca por nombre o correo...",
        amigos_pesquisar_botao: "Buscar",
        amigos_nenhum_encontrado: "No se encontró a nadie con ese nombre o correo.",
        amigos_adicionar: "Añadir",
        amigos_pedido_enviado: "Solicitud enviada",
        amigos_pedidos_pendentes: "Solicitudes pendientes",
        amigos_sem_pedidos: "No hay solicitudes por aceptar.",
        amigos_aceitar: "Aceptar", amigos_recusar: "Rechazar",
        amigos_os_teus: "Tus amigos",
        amigos_sem_amigos: "Todavía no tienes amigos en Gym101%. Busca arriba.",
        amigos_treinos: "entrenamientos",

        des_titulo: "Retos",
        des_subtitulo: "Crea una competición e invita a tus amigos. ¿Quién llega primero a la meta?",
        des_novo: "+ Nuevo reto",
        des_criar_titulo: "Crear reto",
        des_nome: "Nombre del reto", des_nome_placeholder: "Ej: Quién entrena más en octubre",
        des_tipo: "Tipo de competición",
        des_tipo_treinos: "Nº de entrenamientos", des_tipo_calorias: "Calorías quemadas", des_tipo_peso: "Peso perdido",
        des_data_inicio: "Fecha de inicio", des_data_fim: "Fecha de fin",
        des_descricao: "Descripción (opcional)", des_descricao_placeholder: "Reglas, premio para el ganador...",
        des_convidar: "Invitar amigos",
        des_sem_amigos: "Todavía no tienes amigos para invitar. Ve primero a la pestaña Amigos.",
        des_criar_botao: "Crear reto",
        des_sem_desafios: "Todavía no estás en ningún reto. ¡Crea el primero!",
        des_nao_comecou: "Aún no ha empezado", des_terminado: "Finalizado", des_a_decorrer: "En curso",
        des_sem_pontos: "Todavía sin puntos registrados.", des_pts: "pts",
        des_a_carregar: "Cargando retos…"
    }
};
